'use strict';
let studio,state,tab='design',selected='',variantOnly=false,toastTimer,draggedLayer='',keepAspect=true;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let optionLabels={};
const kinds={analog:'Lancette',pointer:'Lancetta piccola',compass:'Bussola analogica',clock:'Ora',date:'Data',number:'Dato live',image:'Immagine',text:'Testo',rect:'Forma',circle:'Cerchio',complication:'Complicazione'};
function toast(message){if(!message)return;$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),8000);}
async function send(action,params={}){
 const response=await new Promise(resolve=>studio.command(JSON.stringify({action,...params}),resolve));
 const result=JSON.parse(response);if(result.error)toast(result.error);const current=!result.state||!state||result.state.stateSequence>=state.stateSequence;if(current&&Object.hasOwn(result,'selectedLayer')){selected=result.selectedLayer;S5Multi.pick(selected);}if(current&&result.state){state=result.state;paint();}return result;
}
function field(label,key,value,type='number',extra=''){return `<label><span class="field">${esc(label)}</span><input class="input" id="prop-${key}" data-prop="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function check(label,key,value){return `<label class="flex items-center gap-2 text-xs text-slate-400 mt-3"><input type="checkbox" data-prop="${key}" ${value?'checked':''}>${esc(label)}</label>`;}
function selectField(label,key,value,options){return `<label class="block mt-3"><span class="field">${esc(label)}</span><select class="input" data-prop="${key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
function editLayer(e,changes){return send(e.kind==='complication'?'edit-slot':'edit',{id:e.id,changes,variantOnly:false});}
function paintChrono(){
 const labels={reset:['Avvia Crono','Crono azzerato'],rest:['Prepara Crono Pro','Secondi dell’ora'],arming:['Posizionamento…','Rientro fluido allo zero'],ready:['Avvia Crono Pro','Crono Pro pronto'],running:['Ferma Crono','Conteggio a scatti'],stopped:['Azzera Crono','Crono fermo'],resetting:['Rientro…','Reset fluido simultaneo']};
 const current=labels[state.chronoState]||labels.reset;$('chrono-preview').textContent=current[0];$('chrono-state').textContent=state.chronoState==='running'&&!state.chronoPro?'Crono in movimento':current[1];$('chrono-preview').disabled=state.aod||['arming','resetting'].includes(state.chronoState);
}
function selectLayer(id){S5Multi.pick(id);setTab('design');}
function paintBuildStatus(){
 $('compile').disabled=state.busy;$('compile').textContent=state.busy?'Compilazione…':'↗ Esporta ZIP';
 $('show-output').classList.toggle('hidden',!state.output);
}
function paint(){
 S5Selectors.close();const inspector=$('properties').parentElement,scroll=inspector.scrollTop,details=[...$('properties').querySelectorAll('details[open]')].map(e=>e.dataset.details);
 optionLabels=state.complicationSources;
 $('motion-preview').checked=state.motionPreview;paintChrono();
 $('project-title').textContent=state.name;$('dirty').textContent=state.dirty?'· modificato':'';
 $('preview').src=state.preview;$('current-style').textContent=state.aod?'AOD comune':state.variants[state.variantIndex].name;
 $('editing-style').innerHTML=state.aod?'<option>AOD comune</option>':state.variants.map((v,i)=>`<option value="${i}" ${i===state.variantIndex?'selected':''}>${esc(v.name)}</option>`).join('');$('editing-style').disabled=state.aod;$('editing-style').onchange=event=>send('select-variant',{index:Number(event.target.value)});
 $('aod').disabled=!state.aodEnabled;$('aod').classList.toggle('active',state.aod);$('normal').classList.toggle('active',!state.aod);
 paintBuildStatus();$('undo').disabled=!state.canUndo;$('redo').disabled=!state.canRedo;
 $('scenario').innerHTML=state.scenarios.map(v=>`<option ${v===state.scenario?'selected':''}>${esc(v)}</option>`).join('');
 for(const k of ['hour','minute','second'])$(k).value=state.values[k]??0;$('compass-heading').value=state.values.systemSensorCompass??135;
 $('validation').textContent=state.errors.join(' · ');
 const layers=state.layers.filter(e=>e.aod===state.aod);if(!layers.some(e=>e.id===selected))selected='';S5Multi.sync(layers);
 $('layers-count').textContent=layers.length+' livelli';
 $('layers').innerHTML=[...layers].reverse().map(e=>`<div class="layer ${S5Multi.has(e.id)?'active':''}" data-layer="${e.id}" draggable="true" tabindex="0" role="button" aria-label="${esc(e.name)}"><span class="drag-grip" aria-hidden="true">⠿</span><button class="layer-icon" data-visible="${e.id}" title="${e.visible?'Nascondi':'Mostra'} livello">${e.visible?'◉':'○'}</button><span class="truncate layer-name">${esc(e.name)}</span><span class="layer-tag">${esc(state.aodExcluded.includes(e.id)?"Esclusa AOD":kinds[e.kind])}</span><button class="layer-icon layer-delete" data-delete-layer="${e.id}" title="Elimina livello" aria-label="Elimina ${esc(e.name)}">×</button></div>`).join('');
 $('layers').querySelectorAll('[data-layer]').forEach(row=>{
  row.onclick=event=>{S5Multi.pick(row.dataset.layer,event.ctrlKey||event.metaKey);paint();};row.onkeydown=event=>{if(event.key==='Enter'){S5Multi.pick(row.dataset.layer,event.ctrlKey||event.metaKey);paint();}};
  row.ondragstart=event=>{draggedLayer=row.dataset.layer;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',draggedLayer);row.classList.add('dragging');};
  row.ondragover=event=>{event.preventDefault();const above=event.clientY<row.getBoundingClientRect().top+row.offsetHeight/2;document.querySelectorAll('.drop-above,.drop-below').forEach(n=>n.classList.remove('drop-above','drop-below'));row.classList.add(above?'drop-above':'drop-below');event.dataTransfer.dropEffect='move';};
  row.ondrop=event=>{event.preventDefault();const id=event.dataTransfer.getData('text/plain')||draggedLayer,placement=event.clientY<row.getBoundingClientRect().top+row.offsetHeight/2?'above':'below';draggedLayer='';send('reorder-layer',{id,targetId:row.dataset.layer,placement});};
  row.ondragend=()=>{draggedLayer='';document.querySelectorAll('.drop-above,.drop-below,.dragging').forEach(n=>n.classList.remove('drop-above','drop-below','dragging'));};
 });
 $('layers').querySelectorAll('[data-delete-layer]').forEach(button=>button.onclick=event=>{event.stopPropagation();send('delete',{id:button.dataset.deleteLayer});});
 $('layers').querySelectorAll('[data-visible]').forEach(button=>button.onclick=event=>{event.stopPropagation();const e=layers.find(e=>e.id===button.dataset.visible);editLayer(e,{visible:!e.visible});});
 paintProperties(layers.find(e=>e.id===selected));S5Multi.inspector();paintCanvas(layers);paintVariants();paintSlots();paintProject();S5Selectors.mount();
 $('properties').querySelectorAll('details').forEach(e=>{if(details.includes(e.dataset.details))e.open=true;});inspector.scrollTop=scroll;
 $('add-complication').disabled=state.aod||state.complications.length>=state.maxSlots;
}
function paintCanvas(layers){
 const root=$('overlays');root.innerHTML='';
 if(!['design','slots'].includes(tab))return;
 for(const e of layers.filter(e=>e.visible&&!state.aodExcluded.includes(e.id))){
  const el=document.createElement('div');el.className='selection '+(S5Multi.has(e.id)?'selected':'');el.title=e.name;el.dataset.element=e.id;el.style.zIndex=e.id===selected?'1':'0';
  Object.assign(el.style,{left:e.x/480*100+'%',top:e.y/480*100+'%',width:e.width/480*100+'%',height:e.height/480*100+'%'});
  el.onpointerdown=event=>canvasGesture(event,e,el);
  if(e.id===selected&&!e.locked&&S5Multi.ids().length===1)for(const corner of ['nw','ne','sw','se']){const handle=document.createElement('span');handle.className='resize-handle '+corner;handle.dataset.resize=corner;handle.title='Trascina per ridimensionare';el.append(handle);}
  root.append(el);
 }
}
function canvasGesture(event,e,el){
 event.preventDefault();event.stopPropagation();S5Multi.pick(e.id,event.ctrlKey||event.metaKey,true);$('canvas').focus({preventScroll:true});
 if(event.ctrlKey||event.metaKey){paint();return;}
 document.querySelectorAll('.selection').forEach(n=>n.classList.toggle('selected',S5Multi.has(n.dataset.element)));
 if(S5Multi.ids().length>1){S5Multi.gesture(event);return;}
 if(e.locked){paint();return;}
 const corner=event.target.dataset.resize,initial={x:e.x,y:e.y,width:e.width,height:e.height},startX=event.clientX,startY=event.clientY;let changes={...initial};
 const move=ev=>{
  const scale=480/$('canvas').getBoundingClientRect().width,dx=Math.round((ev.clientX-startX)*scale),dy=Math.round((ev.clientY-startY)*scale);
  if(!corner){const min=e.kind==='image'?-state.maxImageSize:0,xmax=e.kind==='image'?state.maxImageSize:480-e.width,ymax=e.kind==='image'?state.maxImageSize:480-e.height;changes.x=Math.max(min,Math.min(xmax,e.x+dx));changes.y=Math.max(min,Math.min(ymax,e.y+dy));}
  else{
   const west=corner.includes('w'),north=corner.includes('n'),min=e.kind==='complication'?16:1;
   let width=Math.max(min,e.width+(west?-dx:dx)),height=Math.max(min,e.height+(north?-dy:dy));
   if((e.kind==='image'&&keepAspect)||['analog','pointer','compass'].includes(e.kind)){const factor=Math.max(width/e.width,height/e.height);width=Math.round(e.width*factor);height=Math.round(e.height*factor);}
   let x=west?e.x+e.width-width:e.x,y=north?e.y+e.height-height:e.y;
   if(e.kind==='image'){const factor=Math.min(1,state.maxImageSize/width,state.maxImageSize/height);width=Math.max(1,Math.round(width*factor));height=Math.max(1,Math.round(height*factor));x=west?e.x+e.width-width:e.x;y=north?e.y+e.height-height:e.y;x=Math.max(-state.maxImageSize,Math.min(state.maxImageSize,x));y=Math.max(-state.maxImageSize,Math.min(state.maxImageSize,y));}else{if(x<0){width+=x;x=0;}if(y<0){height+=y;y=0;}width=Math.min(width,480-x);height=Math.min(height,480-y);}
   changes={x,y,width:Math.max(min,width),height:Math.max(min,height)};
  }
  Object.assign(el.style,{left:changes.x/480*100+'%',top:changes.y/480*100+'%',width:changes.width/480*100+'%',height:changes.height/480*100+'%'});
 };
 const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);if(Object.keys(initial).some(k=>changes[k]!==initial[k]))editLayer(e,changes);else paint();};
 window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);
}
function handControls(e,key,label){
 const presets=state.handPresets.filter(p=>e.kind==='pointer'||p.hand===key).sort((a,b)=>e.kind==='pointer'?Number(b.small)-Number(a.small):0),color=e[key+'_color']||e.color,current=presets.find(p=>p.id===e[key+'_preset'])||presets.find(p=>e[key+'_asset']==='assets/'+p.sourceSha256.slice(0,24)+'.png');
 return `<details class="mt-4" data-details="${key}" ${key==='hour'||e.kind==='pointer'?'open':''}><summary class="text-xs text-blue-200 cursor-pointer">${esc(label)}</summary><div class="property-grid mt-3">${field('Colore lancetta',key+'_color',color,'color')}<button class="btn" data-reset-color="${key}">Ripristina colore originale</button>${field('Lunghezza (%)',key+'_length',e[key+'_length'],'number','min="1" max="100"')}${field('Spessore (px)',key+'_width',e[key+'_width'],'number','min="1" max="100"')}</div><div class="card p-3 mt-3"><span class="field">Modelli dai tuoi quadranti · ${presets.length}</span><select class="input" data-preset="${key}"><option value="">Scegli un modello…</option>${presets.map(p=>`<option value="${p.id}" ${p.id===current?.id?'selected':''}>${esc(p.name)} · ${esc(p.theme)} · ${esc(p.author)} · ${p.small?'Piccola · ':''}${p.aod?'AOD · ':''}${p.hand==='indicator'?'Indicatore':({hour:'Ore',minute:'Minuti',second:'Secondi'}[p.hand])} ${p.variant} · ${p.shadow?'con ombra':'senza ombra'} · ${p.id.slice(0,4)}</option>`).join('')}</select><div class="flex items-center gap-3 mt-3"><div class="hand-preview-box"><img hidden id="preset-${key}" class="h-24 w-16 object-contain" alt="Anteprima modello"><span id="preset-empty-${key}" class="text-[10px] text-slate-500">Passa su un modello per vedere l’anteprima</span></div><button data-use-preset="${key}" class="btn flex-1">Usa modello</button></div></div><button data-hand="${key}" class="btn w-full mt-3">Importa PNG / SVG</button><button data-clear-hand="${key}" class="btn w-full mt-2">Usa lancetta disegnata da Studio</button><div id="pivot-${key}" class="pivot-editor mt-3" hidden></div><div class="property-grid mt-3">${field(e.kind==='pointer'?'Pivot manuale X':'Pivot X (−1 auto)',key+'_anchor_x',e[key+'_anchor_x'])}${field(e.kind==='pointer'?'Pivot manuale Y':'Pivot Y (−1 auto)',key+'_anchor_y',e[key+'_anchor_y'])}</div>${e.kind==='pointer'?'<p class="text-[10px] text-slate-500 mt-2">Il perno automatico segue l’estremità visibile. Modificare un pivot manuale disattiva questa opzione.</p>':''}${e[key+'_shadow_asset']?'<p class="text-[10px] text-slate-400 mt-2">Ombra corrispondente abbinata automaticamente.</p>':''}${e[key+'_asset']?'<div class="text-[10px] text-blue-300 mt-2">Immagine incorporata · '+(e.kind==='pointer'?'ridimensionata alla lunghezza scelta':(e[key+'_length_adjusted']||e[key+'_width_adjusted']?'dimensioni regolate':'dimensione originale; regolabile con i controlli'))+'</div>':''}</details>`;
}
function paintProperties(e){
 const root=$('properties');if(!e){root.innerHTML='<div class="text-xs text-slate-500 leading-6">Seleziona un livello sul quadrante o nella lista.<br>Trascina le righe per cambiare l’ordine. I livelli in cima coprono quelli sottostanti.</div>';return;}
 const percent=Math.round(e.opacity*100/255),comp=e.kind==='complication';
 let html=`<div class="border-t border-white/5 pt-5"><div class="flex items-center justify-between mb-4"><h3 class="text-xs font-semibold">${esc(kinds[e.kind])}</h3><button id="delete" class="btn danger">Elimina</button></div>${field('Nome livello','name',e.name,'text')}<div class="property-grid mt-3">${field('Posizione X','x',e.x)}${field('Posizione Y','y',e.y)}${field('Larghezza','width',e.width,'number',`min="1" max="${e.kind==='image'?state.maxImageSize:480}"`)}${field('Altezza','height',e.height,'number',`min="1" max="${e.kind==='image'?state.maxImageSize:480}"`)}</div><div class="property-grid mt-3">${field(e.kind==='image'?'Colore tinta':'Colore','color',e.color,'color')}<label><span class="field">Opacità (%)</span><input id="prop-opacity" class="input" type="number" min="0" max="100" step="1" value="${percent}"></label></div><input id="opacity-range" class="opacity-slider mt-3" type="range" min="0" max="100" step="1" value="${percent}" aria-label="Opacità da 0 a 100"><p class="text-[10px] text-slate-500 mt-1">0 invisibile · 100 completamente visibile</p>`;
 if(['text','number','clock','date','complication'].includes(e.kind))html+=`<div class="mt-3">${field('Dimensione font','size',e.size,'number','min="8" max="160"')}${selectField('Allineamento','align',e.align,[['left','Sinistra'],['center','Centro'],['right','Destra']])}</div>${!comp?'<button id="font-import" class="btn w-full mt-3">Importa font TTF / OTF</button>':''}`;
 if(e.kind==='text')html+=`<div class="mt-3">${field('Testo','text',e.text,'text')}</div>${check('Grassetto','bold',e.bold)}`;
 if(['number','pointer'].includes(e.kind))html+=selectField('Dato che guida '+(e.kind==='pointer'?'la lancetta':'il valore'),'source',state.sourceAliases[e.source]||e.source,Object.entries(e.kind==='pointer'?{...state.pointerSources,...state.luaSources}:state.pointerSources));
 if(e.kind==='number')html+=`<div class="property-grid mt-3">${field('Cifre','digits',e.digits)}${field('Decimali','decimals',e.decimals,'number','min="0" max="3"')}</div>${check('Zeri iniziali','leading_zero',e.leading_zero)}`;
 if(e.kind==='image')html+=`${selectField('Adattamento immagine','fit',e.fit,[['cover','Riempi (ritaglia)'],['contain','Contieni (intera)'],['stretch','Estendi']])}<label class="flex items-center gap-2 text-xs text-slate-400 mt-3"><input id="keep-aspect" type="checkbox" ${keepAspect?'checked':''}>Mantieni proporzioni nel ridimensionamento</label>${check('Applica il colore come tinta','tint',e.tint)}<div class="flex gap-2 mt-3"><button id="image-cover" class="btn flex-1">Riempi quadrante</button><button id="image-contain" class="btn flex-1">Adatta al bordo</button></div><div class="property-grid mt-3"><label><span class="field">Scala (% del quadrante)</span><input id="image-scale" class="input" type="number" min="0.1" max="${Math.floor(state.maxImageSize/480*1000)/10}" step="1" value="${Math.round(e.width/480*1000)/10}"></label><button id="image-center" class="btn">Centra immagine</button></div><p class="text-[10px] text-slate-500 mt-2">Puoi superare i 480 px e spostare l’immagine oltre i bordi. In compilazione viene ritagliata la parte visibile. Frecce: 1 px · Maiusc + frecce: 10 px.</p>`;
 if(e.kind==='analog'){html+=`<p class="text-[11px] text-slate-400 leading-5 mt-4">Il modello ore abbina automaticamente minuti e secondi dello stesso set. Puoi cambiare ciascuna lancetta in seguito. Ogni grafica mantiene la propria ombra e il proprio colore.</p>${check('Tacche del quadrante','show_ticks',e.show_ticks)}${check('Lancetta secondi (schermo normale)','second_hand',e.second_hand)}${check('Mostra le ombre abbinate','show_shadows',e.show_shadows)}`;for(const [key,label] of [['hour','Lancetta ore'],['minute','Lancetta minuti'],['second','Lancetta secondi']]){html+=handControls(e,key,label);if(key==='second'&&!e.aod)html+=check('Crono Pro','chrono_pro',e.chrono_pro)+'<p class="text-[10px] text-slate-500 mt-1">Primo tap prepara, secondo avvia, poi Stop e Reset. Conteggio a scatti; rientri sempre fluidi e coordinati. Disattivato: Crono classico 1.0.</p>';}}
 if(e.kind==='pointer'){html+=`<p class="text-[11px] text-slate-400 leading-5 mt-4">Una lancetta indipendente per sottoquadranti. Il centro del livello è il perno. Per i secondi usa intervallo 60 e rotazione 360°; per batteria usa 100.</p>${check('Perno all’estremità della lancetta','pointer_end_pivot',e.pointer_end_pivot)}${check('Mostra l’ombra abbinata','show_shadows',e.show_shadows)}<div class="property-grid mt-3">${field('Valore iniziale','value_start',e.value_start)}${field('Intervallo valori','value_range',e.value_range,'number','min="1" max="65535"')}${field('Angolo iniziale (°)','angle_start',e.angle_start)}${field('Rotazione totale (°)','angle_range',e.angle_range)}</div>${handControls(e,'second','Grafica lancetta piccola')}`;}
 if(e.kind==='compass'){html+=`<p class="text-[11px] text-slate-400 leading-5 mt-4">Rosa orientata al nord dal sensore bussola reale. Perno sempre al centro, giro inverso di 360°. Larghezza e altezza regolano la dimensione del quadrante.</p>${check('Ricolora la grafica','tint',e.tint)}<div class="card p-3 mt-3"><span class="field">Catalogo bussole · ${state.compassPresets.length}</span><select class="input" id="compass-preset"><option value="">Grafica personalizzata…</option>${state.compassPresets.map(p=>`<option value="${p.id}" ${p.id===e.compass_preset?'selected':''}>${esc(p.label)} · ${esc(p.author)}</option>`).join('')}</select><div class="hand-preview-box mt-3"><img id="compass-preview" class="h-24 w-24 object-contain" hidden alt="Anteprima bussola"></div><button id="compass-apply" class="btn w-full mt-3">Usa modello</button></div><button id="compass-import" class="btn w-full mt-3">Importa PNG / SVG bussola</button>`;}
 if(state.aodExcluded.includes(e.id))html+='<p class="text-[11px] text-amber-200 mt-3">Questa lancetta è sempre esclusa dall’AOD: secondi, decimi e Crono vengono esportati solo nella schermata normale.</p>';
 if(e.kind==='analog'||e.kind==='pointer')html+=check('Movimento Fluido','smooth_seconds',e.smooth_seconds)+'<p class="text-[10px] text-slate-500 mt-1">Crono Pro ignora il flag durante il conteggio: secondi/decimi a scatti. I rientri sono sempre fluidi a 25 fps. In modalità classica il flag mantiene il suo comportamento. Secondi e Crono esclusi dall’AOD.</p>';
 if(e.kind==='pointer'&&Object.hasOwn(state.luaSources,e.source))html+='<p class="text-[11px] text-blue-200 mt-3">Runtime Lua: verifica sul S5. Tocca il quadrantino Crono per Avvia → Ferma → Azzera. Tutte le lancette Crono condividono il conteggio.</p>';
 if(comp)html+=`<p class="text-[11px] text-slate-400 leading-5 mt-4">Il livello nuovo mostra soltanto il valore. Puoi attivare qui decorazioni facoltative.</p><div class="property-grid mt-3">${field('Cifre (0 auto)','digits',e.digits)}${field('Decimali (−1 auto)','decimals',e.decimals)}</div>${selectField('Dato iniziale sull’orologio','default',e.default,e.options.map(k=>[k,optionLabels[k]]))}${selectField('Cornice','frame',e.frame,[['none','Nessuna'],['rounded','Arrotondata'],['circle','Cerchio']])}${check('Mostra etichetta','showLabel',e.showLabel)}${check('Mostra unità','showUnit',e.showUnit)}${field('Unità (vuota = auto)','unit',e.unit,'text')}${selectField('Meteo','weatherMode',e.weatherMode,[['value','Solo valore numerico'],['icon','Icona meteo']])}<button id="slot-options" class="btn primary w-full mt-4">Scegli le informazioni disponibili</button>`;
 html+=check('Visibile','visible',e.visible)+check('Blocca posizione','locked',e.locked)+`<p class="text-[11px] text-blue-200 mt-4">${state.aod?'AOD comune a tutti gli stili.':'Livello indipendente di '+esc(state.variants[state.variantIndex].name)+'.'}</p>`+`<div class="flex gap-2 mt-5"><button id="duplicate" class="btn flex-1">Duplica</button><button id="up-layer" class="btn" title="Porta avanti">↑</button><button id="down-layer" class="btn" title="Porta indietro">↓</button></div></div>`;
 root.innerHTML=html;
 const sourceSelect=root.querySelector('[data-prop=source]');if(sourceSelect)sourceSelect._studioDescription=value=>value==='timeHour'?'Ora completa (0–23): scala di 24 ore = intervallo 24 e 360°; scala di 12 ore = intervallo 24 e 720°.':state.sourceDescriptions[value];
 S5Precision.handPreviews(e);
 root.querySelectorAll('[data-prop]').forEach(input=>input.onchange=()=>{const key=input.dataset.prop,value=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value,changes={[key]:value};if(key==='chrono_pro'&&value)changes.second_hand=true;if(key==='second_hand'&&!value)changes.chrono_pro=false;if(e.kind==='image'&&key==='color')changes.tint=true;if(e.kind==='pointer'&&key.endsWith('_anchor_x')||e.kind==='pointer'&&key.endsWith('_anchor_y'))changes.pointer_end_pivot=false;if(e.kind==='pointer'&&key==='color')changes.second_color=value;if(e.kind==='pointer'&&key==='source'){const ranges={studioDecisecond:[10,360],studioChronoDecisecond:[10,360],studioChronoHour:[12,360],studioChronoMinute:[60,360],studioChronoSecond:[60,360],hour:[24,720],timeHour:[24,720],minute:[60,360],timeMinute:[60,360],second:[60,360],timeSecond:[60,360],batteryPercent:[100,360],systemStatusBattery:[100,360],systemSensorCompass:[360,360],timeHourLow:[10,360],timeHourHigh:[3,360],timeMinuteLow:[10,360],timeMinuteHigh:[6,360],timeSecondLow:[10,360],timeSecondHigh:[6,360]};if(ranges[value]){changes.value_start=0;[changes.value_range,changes.angle_range]=ranges[value];}}if(e.kind==='image'&&keepAspect&&['width','height'].includes(key)){const other=key==='width'?'height':'width';changes[other]=Math.max(1,Math.round(value*e[other]/e[key]));}editLayer(e,changes);});
 const opacityChange=input=>{const percent=Math.round(Number(input.value));if(!Number.isFinite(percent)||percent<0||percent>100){toast('Opacità: inserisci un valore da 0 a 100.');input.value=Math.round(e.opacity*100/255);return;}editLayer(e,{opacity:Math.round(percent*255/100)});};
 $('prop-opacity').onchange=event=>opacityChange(event.target);$('opacity-range').oninput=event=>$('prop-opacity').value=event.target.value;$('opacity-range').onchange=event=>opacityChange(event.target);
 $('duplicate').onclick=()=>send('duplicate',{id:e.id});$('delete').onclick=()=>send('delete',{id:e.id});$('up-layer').onclick=()=>send('move-layer',{id:e.id,direction:1});$('down-layer').onclick=()=>send('move-layer',{id:e.id,direction:-1});
 if($('font-import'))$('font-import').onclick=()=>send('font',{id:e.id});if($('keep-aspect'))$('keep-aspect').onchange=event=>keepAspect=event.target.checked;
 if($('image-center'))$('image-center').onclick=()=>editLayer(e,{x:Math.round((480-e.width)/2),y:Math.round((480-e.height)/2)});
 if($('image-scale'))$('image-scale').onchange=event=>{const width=Math.round(480*Number(event.target.value)/100),factor=width/e.width,height=Math.round(e.height*factor);if(!Number.isFinite(factor)||width<1||height<1||width>state.maxImageSize||height>state.maxImageSize){toast('Dimensioni immagine: da 1 a '+state.maxImageSize+' px.');event.target.value=String(Math.round(e.width/480*1000)/10);return;}editLayer(e,{width,height,x:Math.round(e.x+(e.width-width)/2),y:Math.round(e.y+(e.height-height)/2)});};
 for(const fit of ['cover','contain'])if($('image-'+fit))$('image-'+fit).onclick=()=>send('fit-image',{id:e.id,fit,variantOnly});
 if($('slot-options'))$('slot-options').onclick=()=>{setTab('slots');document.querySelector('[data-slot="'+e.id+'"]').scrollIntoView({block:'center'});};
 if($('compass-preset')){
  const input=$('compass-preset');input._studioGraphic=value=>{const p=state.compassPresets.find(p=>p.id===value);return p?{src:p.thumbnail,label:p.label}:null;};
  const show=value=>{const graphic=input._studioGraphic(value),img=$('compass-preview');img.hidden=!graphic;if(graphic)img.src=graphic.src;else img.removeAttribute('src');};
  input.addEventListener('studio-option-preview',event=>show(event.detail.value));input.onchange=()=>{show(input.value);$('compass-apply').disabled=!input.value;};input.onchange();
  $('compass-apply').onclick=()=>send('compass-preset',{id:e.id,preset:input.value,variantOnly});$('compass-import').onclick=()=>send('compass-image',{id:e.id,variantOnly});
 }
 root.querySelectorAll('[data-preset]').forEach(input=>{
  const hand=input.dataset.preset;
  input._studioGraphic=value=>{const preset=state.handPresets.find(p=>p.id===value);return preset?{src:preset.thumbnail,label:preset.name+' · '+preset.theme+(preset.shadow?' · ombra abbinata':'')}:null;};
  const show=value=>{const graphic=input._studioGraphic(value),img=$('preset-'+hand),empty=$('preset-empty-'+hand);img.hidden=!graphic;empty.hidden=Boolean(graphic);if(graphic){if(img.getAttribute('src')!==graphic.src)img.src=graphic.src;img.alt=graphic.label;}else img.removeAttribute('src');};
  input.addEventListener('studio-option-preview',event=>show(event.detail.value));
  input.onchange=()=>{show(input.value);root.querySelector('[data-use-preset="'+hand+'"]').disabled=!input.value;};input.onchange();
 });
 root.querySelectorAll('[data-use-preset]').forEach(button=>button.onclick=()=>{const hand=button.dataset.usePreset,preset=root.querySelector('[data-preset="'+hand+'"]').value;if(preset)send('hand-preset',{id:e.id,hand,preset,variantOnly});});
 root.querySelectorAll('[data-reset-color]').forEach(button=>button.onclick=()=>editLayer(e,{[button.dataset.resetColor+'_color']:''}));
 root.querySelectorAll('[data-clear-hand]').forEach(button=>button.onclick=()=>send('clear-hand',{id:e.id,hand:button.dataset.clearHand,variantOnly}));
 root.querySelectorAll('[data-hand]').forEach(button=>button.onclick=()=>send('hand-image',{id:e.id,hand:button.dataset.hand,variantOnly}));
}
function paintVariants(){
  const root=$('variants-panel'),v=state.variants[state.variantIndex];
  root.innerHTML=`<div class="flex justify-between items-center mb-4"><h3 class="text-sm font-semibold">${state.variants.length} / 5 stili con livelli indipendenti</h3><button id="variant-add" class="btn primary" ${state.variants.length>=5?'disabled':''}>＋ Duplica stile</button></div><div class="grid grid-cols-5 gap-3 mb-5">${state.variants.map((v,i)=>`<button class="variant-card ${i===state.variantIndex?'active':''}" data-variant="${i}"><img src="${state.thumbnails[i]}" alt="${esc(v.name)}"><div class="text-[11px] mt-3 truncate">${esc(v.name)}</div></button>`).join('')}</div><div class="card p-5"><div class="grid grid-cols-3 gap-4">${field('Nome stile','variant-name',v.name,'text')}${field('Colore accento','variant-accent',v.accent,'color')}${field('Sfondo','variant-background',v.background||state.background,'color')}</div><div class="flex gap-2 mt-4"><button id="variant-image" class="btn">＋ Sfondo da immagine</button><button id="variant-reset-image" class="btn">Rimuovi sfondo</button><button id="variant-edit" class="btn">Apri livelli di questo stile</button><button id="variant-delete" class="btn ml-auto" ${state.variants.length===1?'disabled':''}>Elimina stile</button></div><p class="text-[11px] text-slate-500 leading-5 mt-4">Ogni stile possiede i propri livelli, sfondi, lancette e complicazioni. Duplica lo stile selezionato e modifica la copia: aggiunte, eliminazioni, colori e posizioni restano indipendenti. Cambia stile anche dal selettore nel pannello Livelli e proprietà. L’AOD resta comune.</p></div>`;
  root.querySelectorAll('[data-variant]').forEach(el=>el.onclick=()=>send('select-variant',{index:Number(el.dataset.variant)}));
  $('variant-add').onclick=()=>send('add-variant');$('variant-delete').onclick=()=>send('delete-variant');$('variant-image').onclick=()=>send('variant-image');$('variant-reset-image').onclick=()=>send('edit-variant',{changes:{imageAsset:''}});$('variant-edit').onclick=()=>{setTab('design');$('inspector').scrollTop=0;};
  for(const key of ['name','accent','background'])$('prop-variant-'+key).onchange=event=>send('edit-variant',{changes:{[key]:event.target.value}});
}
function paintSlots(){
 const root=$('slots-panel');root.innerHTML=`<div class="flex justify-between items-center mb-4"><h3 class="text-sm font-semibold">${state.complications.length} complicazioni indipendenti</h3><button id="slot-add" class="btn primary" ${state.complications.length>=state.maxSlots?'disabled':''}>＋ Aggiungi complicazione</button></div><p class="text-[11px] text-slate-500 leading-5 mb-4">Ogni complicazione è un livello: spostala e riordinala nella scheda Quadrante. I nuovi livelli mostrano soltanto il valore. Qui scegli quali informazioni saranno selezionabili sull’orologio (fino a ${state.maxSlots} livelli).</p>${state.complications.map(slot=>`<div class="card p-5 mb-4" data-slot="${slot.id}"><div class="flex justify-between mb-4"><h4 class="text-sm font-semibold">${esc(slot.name)}</h4><div class="flex gap-2"><button data-edit-layer="${slot.id}" class="btn">Posizione e stile</button><button data-delete-slot="${slot.id}" class="btn danger">Elimina</button></div></div><details open><summary class="text-xs text-blue-200 cursor-pointer mb-3">Informazioni selezionabili · ${slot.options.length} abilitate</summary><input data-filter class="input mb-3" placeholder="Cerca un dato, es. meteo o pulsazioni"><div class="grid grid-cols-3 gap-2 max-h-64 overflow-y-auto">${Object.entries(optionLabels).map(([key,label])=>`<label class="choice"><input type="checkbox" data-choice="${key}" ${slot.options.includes(key)?'checked':''}>${esc(label)}</label>`).join('')}</div></details><div class="grid grid-cols-2 gap-4 mt-4"><label><span class="field">Opzione iniziale sull’orologio</span><select data-slot-prop="default" class="input">${slot.options.map(key=>`<option value="${key}" ${key===slot.default?'selected':''}>${esc(optionLabels[key])}</option>`).join('')}</select></label><label><span class="field">Simula selezione nell’anteprima</span><select data-simulate class="input">${slot.options.map(key=>`<option value="${key}" ${key===(state.values.__choices?.[slot.id]||slot.default)?'selected':''}>${esc(optionLabels[key])}</option>`).join('')}</select></label></div></div>`).join('')}${!state.complications.length?'<div class="card p-6 text-xs text-slate-500 text-center">Aggiungi una complicazione e scegli i dati da rendere selezionabili.</div>':''}`;
 $('slot-add').onclick=()=>send('add-slot');root.querySelectorAll('[data-delete-slot]').forEach(el=>el.onclick=()=>send('delete',{id:el.dataset.deleteSlot}));root.querySelectorAll('[data-edit-layer]').forEach(el=>el.onclick=()=>selectLayer(el.dataset.editLayer));
 root.querySelectorAll('[data-slot]').forEach(card=>{
  const id=card.dataset.slot,slot=state.complications.find(s=>s.id===id);
  card.querySelector('[data-slot-prop]').onchange=event=>send('edit-slot',{id,changes:{default:event.target.value}});
  card.querySelector('[data-filter]').oninput=event=>card.querySelectorAll('.choice').forEach(c=>c.classList.toggle('hidden',!c.textContent.toLowerCase().includes(event.target.value.toLowerCase())));
  card.querySelector('[data-simulate]').onchange=event=>send('slot-preview',{id,choice:event.target.value});
  card.querySelectorAll('[data-choice]').forEach(input=>input.onchange=()=>{const options=[...card.querySelectorAll('[data-choice]:checked')].map(n=>n.dataset.choice);if(!options.length){input.checked=true;toast('Mantieni almeno un’informazione selezionabile.');return;}send('edit-slot',{id,changes:{options,default:options.includes(slot.default)?slot.default:options[0]}});});
 });
}
function paintProject(){
  const root=$('project-panel');
  root.innerHTML=`<div class="card p-5 mb-4"><h3 class="text-sm font-semibold mb-4">Identità del progetto</h3><div class="grid grid-cols-2 gap-4">${field('Nome progetto','project-name',state.name,'text')}${field('Autore','project-author',state.author,'text')}${field('Versione progetto','project-version',state.version,'text')}${field('ID quadrante','project-faceId',state.faceId,'text')}${field('Sfondo dello stile attivo','project-background',state.background,'color',state.aod?'disabled':'')}</div><p class="text-[11px] text-slate-500 leading-5 mt-4">Nome, stili, risorse e anteprime vengono rigenerati dal progetto. L'uploader locale della mod può comunque mostrare L00000000001 dal proprio catalogo.</p></div><div class="card p-5 mb-4"><h3 class="text-sm font-semibold">Always on display</h3><label class="flex items-center gap-2 text-xs text-slate-400 mt-4"><input type="checkbox" id="aod-enabled" ${state.aodEnabled?'checked':''}>Includi la schermata AOD</label><p class="text-[11px] text-slate-500 leading-5 mt-3">Apri la scheda AOD per modificarla. Viene abbinata a ogni stile; la lancetta dei secondi è esclusa nell’AOD.</p></div><div class="card p-5"><h3 class="text-sm font-semibold mb-3">Dal progetto all’orologio</h3><ol class="text-xs text-slate-400 leading-7 list-decimal pl-4"><li>Salva il progetto, poi premi “Esporta ZIP”.</li><li>Copia il file *_TEMPLATE.zip sul telefono senza estrarlo.</li><li>Apri Local watchfaces uploader con il S5 sincronizzato.</li><li>Se compare l’errore capabilities, disattiva Verify capability test come nella tua prova riuscita.</li><li>Installa e prova lancette, stili, complicazioni e AOD.</li></ol><p class="text-[11px] text-slate-500 mt-3 leading-5">La preview assente nella lista locale della mod è stata osservata anche col template. Il test reale NASA creato con la 0.8 è stato superato sul tuo S5. Il test reale della 0.9, bussola compresa, è superato. Movimento fluido e decimi confermati sul S5. Crono 1.0 e decimi collaudati sul S5. Test reale 1.2 superato, Crono Pro e stili indipendenti inclusi. La 1.3 porta i rientri a 480 ms: velocit? ridotta di un terzo.</p><button id="compiler-select" class="btn mt-4">Seleziona Compiler.exe</button></div>`;
  for(const key of ['name','author','version','background','faceId'])$('prop-project-'+key).onchange=event=>send('settings',{changes:{[key]:event.target.value}});
  $('aod-enabled').onchange=event=>send('settings',{changes:{aodEnabled:event.target.checked}});$('compiler-select').onclick=()=>send('compiler');
}
function setTab(value){
  S5Selectors.close();tab=value;const labels={design:['Quadrante','Disegna il tuo tempo','Immagini, lancette e dati. Tutto in un unico quadrante.'],variants:['Varianti grafiche','Uno stile, cinque possibilità','Crea varianti di colore, immagini e disposizione.'],slots:['Complicazioni','Dati che si adattano a te','Scegli cosa rendere modificabile dal quadrante.'],project:['Progetto e AOD','Pronto per il tuo S5','Impostazioni, schermo sempre acceso e trasferimento.']};
  $('tab-label').textContent=labels[value][0];$('view-title').textContent=labels[value][1];$('view-subtitle').textContent=labels[value][2];
  document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===value));
  for(const name of ['design','variants','slots','project'])$(name+'-panel').classList.toggle('hidden',name!==value);
  $('stage-wrap').classList.toggle('hidden',value==='project');$('simulation').classList.toggle('hidden',value==='project');
  if(state)paint();
}
new QWebChannel(qt.webChannelTransport,channel=>{
  studio=channel.objects.studio;
  studio.event.connect(raw=>{const event=JSON.parse(raw);if(event.state&&(!state||event.state.stateSequence>=state.stateSequence)){state=event.state;paint();}if(event.buildStatus&&state&&event.buildStatus.stateSequence>=state.stateSequence){Object.assign(state,event.buildStatus);paintBuildStatus();}if(event.preview){$('preview').src=event.preview;state.preview=event.preview;state.values=event.previewValues;if(event.chronoState){state.chronoState=event.chronoState;paintChrono();}}if(event.error)toast(event.error);if(event.progress)$('status').textContent=event.progress;if(event.buildDone)toast('ZIP esportato. Apri la cartella per copiarlo sul telefono.');});
  document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>setTab(el.dataset.tab));
  document.querySelectorAll('[data-template]').forEach(el=>el.onclick=()=>send('new',{template:el.dataset.template}));
  document.querySelectorAll('[data-add]').forEach(el=>el.onclick=()=>send('add',{kind:el.dataset.add}));
  for(const [id,action] of [['open','open'],['save','save'],['compile','build'],['import','image'],['undo','undo'],['redo','redo'],['preview-export','export-preview'],['show-output','show-output']])$(id).onclick=()=>send(action);
  $('add-complication').onclick=()=>send('add-slot');$('chrono-preview').onclick=()=>send('chrono-preview');$('motion-preview').onchange=event=>send('motion-preview',{value:event.target.checked});
  $('normal').onclick=()=>send('aod',{value:false});$('aod').onclick=()=>send('aod',{value:true});$('scenario').onchange=event=>send('scenario',{value:event.target.value});
  for(const k of ['hour','minute','second','systemSensorCompass'])$(k==='systemSensorCompass'?'compass-heading':k).onchange=event=>send('time',{[k]:Number(event.target.value)});
  window.addEventListener('keydown',event=>{
   if(event.defaultPrevented)return;
   const editing=document.activeElement?.matches('input,textarea,select,[contenteditable=true]')||(event.target instanceof Element&&event.target.matches('input,textarea,select,[contenteditable=true]'));
   const arrows={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};
   if(arrows[event.key]&&selected&&!editing&&!S5Selectors.isOpen()&&['design','slots'].includes(tab)&&!event.ctrlKey&&!event.metaKey&&!event.altKey){event.preventDefault();const [dx,dy]=arrows[event.key],step=event.shiftKey?10:1;if(S5Multi.ids().length>1)send('move-group',{ids:S5Multi.ids(),dx:dx*step,dy:dy*step,variantOnly});else send('nudge',{id:selected,dx:dx*step,dy:dy*step,variantOnly});return;}
   if(event.key==='Delete'&&selected&&!editing&&!S5Selectors.isOpen()){event.preventDefault();send('delete',{id:selected});return;}
   if((event.ctrlKey||event.metaKey)&&['s','z','y','o'].includes(event.key.toLowerCase())){event.preventDefault();send({s:'save',z:'undo',y:'redo',o:'open'}[event.key.toLowerCase()]);}
  });
  S5Precision.mount();window.s5Ready=true;send('state');
});
